import { expect, test } from '@playwright/test'

test('OIDC login, create, edit, read and search a document', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.locator('[data-test="login-link"]').click()
  await expect(page.locator('[data-test="login-page"]')).toBeVisible()
  await page.locator('[data-test="sso-btn"]').click()
  await expect(page.locator('[data-test="idp-admin"]')).toBeVisible()
  await page.locator('[data-test="idp-admin"]').click()

  await expect(page.locator('[data-test="nav-create"]')).toBeVisible()
  await expect(page.locator('[data-test="nav-admin"]')).toBeVisible()
  await page.locator('[data-test="nav-create"]').click()
  await page.locator('[data-test="create-title"]').fill('Acceptance Guide')
  await page.locator('[data-test="create-submit"]').click()

  await expect(page.locator('[data-test="edit-page"]')).toBeVisible()
  await page.locator('[data-test="md-source"]').fill('# Acceptance Guide\n\nUnique browser flow phrase')
  await page.locator('[data-test="save-exit"]').click()
  await expect(page.locator('[data-test="doc-page"]')).toBeVisible()
  await expect(page.locator('[data-test="doc-html"]')).toContainText('Unique browser flow phrase')
  await page.screenshot({ path: testInfo.outputPath('document.png'), fullPage: true })

  await page.getByRole('link', { name: 'Search' }).click()
  await page.locator('[data-test="search-input"]').fill('Unique browser flow phrase')
  await page.locator('[data-test="search-submit"]').click()
  await expect(page.locator('[data-test="search-hits"]')).toContainText('Acceptance Guide')
  await page.locator('[data-test="search-hits"] a').click()
  await expect(page.locator('[data-test="doc-html"]')).toContainText('Unique browser flow phrase')

  await page.locator('[data-test="nav-admin"]').click()
  await expect(page.locator('[data-test="tab-settings"]')).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('admin.png'), fullPage: true })

  await page.getByRole('tab', { name: 'Document tree' }).click()
  const treeRow = page.locator('[data-test="admin-tree-row"]').filter({ hasText: 'Acceptance Guide' })
  await treeRow.hover()
  await treeRow.locator('[data-test="admin-tree-trash"]').click()
  await page.locator('[data-test="nav-trash"]').click()
  const trashRow = page.locator('[data-test="trash-item"]').filter({ hasText: 'Acceptance Guide' })
  await expect(trashRow).toBeVisible()
  await trashRow.getByRole('button', { name: 'Delete forever' }).click()
  await expect(page.locator('.el-message-box')).toContainText('Acceptance Guide')
  await page.locator('.el-message-box__btns .el-button').first().click()
  await expect(trashRow).toBeVisible()
  await trashRow.getByRole('button', { name: 'Delete forever' }).click()
  await page.locator('.el-message-box__btns .el-button--primary').click()
  await expect(trashRow).toHaveCount(0)
})
