import { expect, test } from '@playwright/test'

test('OIDC users can edit, search and manage trash by permission', async ({ page, browser }, testInfo) => {
  await page.goto('/')
  await page.locator('[data-test="login-link"]').click()
  await expect(page.locator('[data-test="login-page"]')).toBeVisible()
  await page.locator('[data-test="sso-btn"]').click()
  await expect(page.locator('[data-test="idp-admin"]')).toBeVisible()
  await page.locator('[data-test="idp-admin"]').click()

  await expect(page.locator('[data-test="nav-create"]')).toBeVisible()
  await expect(page.locator('[data-test="nav-admin"]')).toBeVisible()
  await page.locator('[data-test="nav-create"]').click()
  await page.keyboard.press('Control+Shift+F')
  await expect(page.locator('[data-test="create-title"]')).toBeVisible()
  await expect(page).not.toHaveURL(/\/search$/)
  await page.keyboard.press('Escape')
  await expect(page.locator('[data-test="create-title"]')).toBeHidden()
  await page.locator('[data-test="nav-create"]').click()
  await page.locator('[data-test="create-title"]').fill('Acceptance Guide')
  await page.locator('[data-test="create-submit"]').click()

  await expect(page.locator('[data-test="edit-page"]')).toBeVisible()
  await page.locator('[data-test="md-source"]').fill('# Acceptance Guide\n\nUnique browser flow phrase')
  await page.locator('[data-test="save-exit"]').click()
  await expect(page.locator('[data-test="doc-page"]')).toBeVisible()
  await expect(page.locator('[data-test="doc-html"]')).toContainText('Unique browser flow phrase')
  const docURL = page.url()
  await page.screenshot({ path: testInfo.outputPath('document.png'), fullPage: true })

  await page.getByRole('link', { name: 'Search' }).click()
  await page.locator('[data-test="search-input"]').fill('Unique browser flow phrase')
  await page.locator('[data-test="search-submit"]').click()
  await expect(page.locator('[data-test="search-hits"]')).toContainText('Acceptance Guide')
  await page.locator('[data-test="search-hits"] a').click()
  await expect(page.locator('[data-test="doc-html"]')).toContainText('Unique browser flow phrase')

  await page.locator('[data-test="nav-admin"]').click()
  await expect(page.locator('[data-test="tab-settings"]')).toBeVisible()
  await page.locator('[data-test="f-tz"]').fill('Europe/Berlin')
  await page.locator('[data-test="admin-save"]').click()
  await expect(page.locator('[data-test="settings-change-state"]')).toHaveText('Settings are saved')
  await page.goto(docURL)
  await page.locator('[data-test="btn-history"]').click()
  await expect(page.locator('[data-test="history-drawer"]')).toContainText('(Europe/Berlin)')
  await page.keyboard.press('Escape')
  await page.locator('[data-test="nav-admin"]').click()
  await page.screenshot({ path: testInfo.outputPath('admin.png'), fullPage: true })

  await page.getByRole('tab', { name: 'Document tree' }).click()
  const treeRow = page.locator('[data-test="admin-tree-row"]').filter({ hasText: 'Acceptance Guide' })
  await treeRow.hover()
  await treeRow.locator('[data-test="admin-tree-trash"]').click()
  await page.locator('[data-test="nav-trash"]').click()
  const trashRow = page.locator('[data-test="trash-item"]').filter({ hasText: 'Acceptance Guide' })
  await expect(trashRow).toBeVisible()
  await trashRow.getByRole('button', { name: 'Delete forever' }).click()
  await expect(page.locator('.el-message-box')).toContainText('Acceptance Guide')
  await page.locator('.el-message-box__btns .el-button').first().click()
  await expect(trashRow).toBeVisible()
  await trashRow.getByRole('button', { name: 'Delete forever' }).click()
  await page.locator('.el-message-box__btns .el-button--primary').click()
  await expect(trashRow).toHaveCount(0)

  const viewerContext = await browser.newContext({ baseURL: 'http://127.0.0.1:5175' })
  try {
    const viewerPage = await viewerContext.newPage()
    await viewerPage.goto('/login')
    await viewerPage.locator('[data-test="sso-btn"]').click()
    await viewerPage.locator('[data-test="idp-viewer"]').click()
    await expect(viewerPage.locator('[data-test="nav-create"]')).toHaveCount(0)
    await expect(viewerPage.locator('[data-test="nav-admin"]')).toHaveCount(0)

    await page.locator('[data-test="nav-admin"]').click()
    await page.getByRole('tab', { name: 'Users' }).click()
    const viewerRow = page.locator('[data-test="admin-users"] tr').filter({ hasText: 'viewer@e2e.local' })
    await expect(viewerRow).toBeVisible()
    await viewerRow.locator('select').selectOption('editor')
    await expect(viewerRow.locator('select')).toHaveValue('editor')

    await viewerPage.reload()
    const editorAdminLink = viewerPage.locator('[data-test="nav-admin"]')
    await expect(editorAdminLink).toHaveAttribute('href', '/admin?tab=tree')
    await editorAdminLink.click()
    await expect(viewerPage.locator('[data-test="tab-tree"]')).toBeVisible()
  } finally {
    await viewerContext.close()
  }
})
