import { expect, test } from '@playwright/test'

test('OIDC users can edit, search and manage trash by permission', async ({ page, browser }, testInfo) => {
  test.setTimeout(90000)
  await page.goto('/')
  await page.locator('[data-test="login-link"]').click()
  await expect(page.locator('[data-test="login-page"]')).toBeVisible()
  await page.locator('[data-test="sso-btn"]').click()
  await expect(page.locator('[data-test="idp-admin"]')).toBeVisible()
  await page.locator('[data-test="idp-admin"]').click()

  await expect(page.locator('[data-test="nav-create"]')).toBeVisible()
  await expect(page.locator('[data-test="nav-admin"]')).toBeVisible()
  await page.setViewportSize({ width: 375, height: 800 })
  await expect(page.locator('[data-test="m-search"]')).toBeVisible()
  await expect(page.locator('[data-test="m-create"]')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(375)
  await page.locator('[data-test="nav-menu"]').click()
  await expect(page.locator('[data-test="m-admin"]')).toBeVisible()
  await page.keyboard.press('Escape')
  await page.setViewportSize({ width: 1280, height: 720 })
  await page.locator('[data-test="nav-create"]').click()
  await page.keyboard.press('Control+Shift+F')
  await expect(page.locator('[data-test="create-title"]')).toBeVisible()
  await expect(page).not.toHaveURL(/\/search$/)
  await page.keyboard.press('Escape')
  await expect(page.locator('[data-test="create-title"]')).toBeHidden()
  await page.locator('[data-test="nav-create"]').click()
  await page.locator('[data-test="create-title"]').fill('Acceptance Guide')
  await page.locator('[data-test="create-submit"]').click()

  await expect(page.locator('[data-test="edit-page"]')).toBeVisible()
  await expect(page.locator('[data-test="md-source"]')).toBeVisible()
  await expect(page.locator('[data-test="preview-pane"]')).toBeVisible()
  await page.setViewportSize({ width: 375, height: 800 })
  await expect(page.locator('[data-test="md-source"]')).toBeVisible()
  await expect(page.locator('[data-test="preview-pane"]')).toHaveCount(0)
  expect(await page.locator('[data-test="md-source"]').evaluate((el) => el.getBoundingClientRect().width)).toBeGreaterThan(250)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(375)
  expect(await page.locator('main').evaluate((el) => el.scrollWidth)).toBeLessThanOrEqual(
    await page.locator('main').evaluate((el) => el.clientWidth),
  )
  await page.locator('[data-test="preview-toggle"]').click()
  await expect(page.locator('[data-test="preview-pane"]')).toBeVisible()
  await expect(page.locator('[data-test="preview-empty"]')).toBeVisible()
  expect(await page.locator('main').evaluate((el) => el.scrollWidth)).toBeLessThanOrEqual(
    await page.locator('main').evaluate((el) => el.clientWidth),
  )
  await expect(page.locator('[data-test="md-source"]')).toBeHidden()
  await page.locator('[data-test="preview-toggle"]').click()
  await expect(page.locator('[data-test="md-source"]')).toBeVisible()
  await page.locator('[data-test="md-source"]').fill('# Acceptance Guide\n\nUnique browser flow phrase')
  await page.locator('[data-test="save-exit"]').click()
  await expect(page.locator('[data-test="doc-page"]')).toBeVisible()
  await expect(page.locator('[data-test="doc-html"]')).toContainText('Unique browser flow phrase')
  await page.setViewportSize({ width: 1280, height: 720 })
  await expect.poll(() => page.locator('[data-test="doc-content-card"]').evaluate((el) => el.getBoundingClientRect().width)).toBeGreaterThan(700)
  expect(await page.evaluate(() => getComputedStyle(document.querySelector('[data-test="main-scroll-region"]')!).overflowY)).toBe('auto')
  expect(await page.evaluate(() => document.documentElement.scrollHeight - document.documentElement.clientHeight)).toBeLessThanOrEqual(1)
  const docURL = page.url()
  await page.screenshot({ path: testInfo.outputPath('document.png'), fullPage: true })

  await page.getByRole('link', { name: 'Search' }).click()
  await page.locator('[data-test="search-input"]').fill('Unique browser flow phrase')
  await page.locator('[data-test="search-submit"]').click()
  await expect(page.locator('[data-test="search-hits"]')).toContainText('Acceptance Guide')
  await page.locator('[data-test="search-hits"] a').click()
  await expect(page.locator('[data-test="doc-html"]')).toContainText('Unique browser flow phrase')

  await page.locator('[data-test="nav-admin"]').click()
  await expect(page.locator('[data-test="tab-settings"]')).toBeVisible()
  await page.locator('[data-test="f-tz"]').selectOption('Europe/Berlin')
  await page.locator('[data-test="f-deployment-preset"]').selectOption('public_readonly')
  await expect(page.locator('.el-message-box').first()).toBeVisible()
  await page.locator('.el-message-box__btns .el-button--primary').click()
  await expect(page.locator('.el-message-box')).toHaveCount(0)
  await expect(page.locator('[data-test="f-anon"]')).toHaveClass(/is-checked/)
  await expect(page.locator('[data-test="f-comments"]')).not.toHaveClass(/is-checked/)
  await expect(page.locator('[data-test="f-user-pages"]')).not.toHaveClass(/is-checked/)
  await page.locator('[data-test="f-deployment-preset"]').selectOption('public_contributions')
  await expect(page.locator('.el-message-box').first()).toBeVisible()
  await page.locator('.el-message-box__btns .el-button--primary').click()
  await expect(page.locator('.el-message-box')).toHaveCount(0)
  await expect(page.locator('[data-test="f-user-pages"]')).toHaveClass(/is-checked/)
  await expect(page.locator('[data-test="f-user-pages-review"]')).toHaveClass(/is-checked/)
  await expect(page.locator('[data-test="f-document-review"]')).toHaveClass(/is-checked/)
  await page.locator('[data-test="theme-advanced"] summary').click()
  await page.locator('[data-test="theme_light_primary"]').evaluate((el) => {
    const input = el as HTMLInputElement
    input.value = '#1D4ED8'
    input.dispatchEvent(new Event('input', { bubbles: true }))
    input.dispatchEvent(new Event('change', { bubbles: true }))
  })
  await page.locator('[data-test="article-footer-markdown"]').fill('**Site notice** [ICP备案](https://beian.miit.gov.cn/)')
  await page.locator('[data-test="sidebar-footer-markdown"]').fill('[京ICP备示例号](https://beian.miit.gov.cn/)')
  await page.locator('[data-test="admin-save"]').click()
  await expect(page.locator('[data-test="settings-change-state"]')).toHaveText('Settings are saved')
  await page.locator('[data-test="account-menu-toggle"]').click()
  await page.locator('[data-test="nav-tokens"]').click()
  await expect(page.locator('[data-test="tokens-page"]')).toBeVisible()
  await page.locator('[data-test="token-name"]').fill('Browser revoke check')
  await page.locator('[data-test="token-create"]').click()
  const tokenRow = page.locator('[data-test="token-row"]').filter({ hasText: 'Browser revoke check' })
  await expect(tokenRow).toBeVisible()
  const revokeResponse = page.waitForResponse((response) =>
    response.request().method() === 'DELETE' && /\/v1\/tokens\//.test(response.url()),
  )
  await tokenRow.locator('[data-test="token-revoke"]').click()
  expect((await revokeResponse).status()).toBe(204)
  await expect(tokenRow.locator('[data-test="token-revoked"]')).toBeVisible()
  await expect(tokenRow.locator('[data-test="token-revoke"]')).toHaveCount(0)
  await expect(page.locator('[data-test="token-revoke-error"]')).toHaveCount(0)
  await expect(page.locator('[data-test="settings-title"]')).toBeVisible()
  await page.locator('[data-test="settings-language"]').selectOption('en')
  await page.locator('[data-test="settings-theme"]').selectOption('system')
  await page.locator('[data-test="settings-save-preferences"]').click()
  await page.reload()
  await expect(page.locator('[data-test="settings-language"]')).toHaveValue('en')
  await expect(page.locator('[data-test="settings-theme"]')).toHaveValue('system')
  await page.locator('[data-test="settings-theme"]').selectOption('dark')
  await page.locator('[data-test="settings-save-preferences"]').click()
  await expect(page.locator('html')).toHaveClass(/dark/)
  expect(await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--color-danger').trim())).toBe('#fca5a5')
  expect(await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--color-warning').trim())).toBe('#fcd34d')
  await page.locator('[data-test="settings-theme"]').selectOption('light')
  await page.locator('[data-test="settings-save-preferences"]').click()
  await expect(page.locator('html')).not.toHaveClass(/dark/)
  expect(await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--color-danger').trim())).toBe('#b91c1c')
  expect(await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--color-success').trim())).toBe('#15803d')
  await page.locator('[data-test="settings-theme"]').selectOption('system')
  await page.locator('[data-test="settings-save-preferences"]').click()
  await page.goto(docURL)
  await expect(page.locator('[data-test="article-footer"]')).toContainText('Site notice')
  await expect(page.locator('[data-test="site-sidebar-markdown"]')).toContainText('京ICP备示例号')
  await expect(page.locator('[data-test="site-sidebar-footer"]')).not.toContainText('Element Wiki')
  expect(await page.locator('[data-test="site-sidebar-markdown"]').evaluate((el) => getComputedStyle(el).fontSize)).toBe('12px')
  await expect(page.locator('[data-test="tree-item"].tree-nav-item-active')).toContainText('Acceptance Guide')
  expect((await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--site-primary-light').trim())).toLowerCase()).toBe('#1d4ed8')
  await expect(page.locator('[data-test="toc-panel"]')).toBeVisible()
  await expect(page.locator('[data-test="toc-link"][aria-current="location"]')).toHaveCount(1)
  await page.locator('[data-test="btn-more"]').click()
  const printPopup = page.waitForEvent('popup')
  await page.locator('[data-test="btn-print"]').click()
  const printPage = await printPopup
  await expect(printPage.locator('[data-test="print-article-footer"]')).toContainText('Site notice')
  await printPage.close()
  await page.locator('[data-test="btn-history"]').click()
  await expect(page.locator('[data-test="history-drawer"]')).toContainText('(Europe/Berlin)')
  await page.keyboard.press('Escape')
  await page.locator('[data-test="nav-admin"]').click()
  await page.screenshot({ path: testInfo.outputPath('admin.png'), fullPage: true })

  await page.getByRole('tab', { name: 'Document tree' }).click()
  const treeRow = page.locator('[data-test="admin-tree-row"]').filter({ hasText: 'Acceptance Guide' })
  await treeRow.hover()
  await treeRow.locator('[data-test="admin-tree-trash"]').click()
  await page.locator('[data-test="account-menu-toggle"]').click()
  await page.locator('[data-test="nav-trash"]').click()
  const trashRow = page.locator('[data-test="trash-item"]').filter({ hasText: 'Acceptance Guide' })
  await expect(trashRow).toBeVisible()
  await trashRow.getByRole('button', { name: 'Delete forever' }).click()
  await expect(page.locator('.el-message-box')).toContainText('Acceptance Guide')
  await page.locator('.el-message-box__btns .el-button').first().click()
  await expect(trashRow).toBeVisible()
  await trashRow.getByRole('button', { name: 'Delete forever' }).click()
  await page.locator('.el-message-box__btns .el-button--primary').click()
  await expect(trashRow).toHaveCount(0)

  const viewerContext = await browser.newContext({ baseURL: new URL(page.url()).origin })
  try {
    const viewerPage = await viewerContext.newPage()
    await viewerPage.goto('/login')
    await viewerPage.locator('[data-test="sso-btn"]').click()
    await viewerPage.locator('[data-test="idp-viewer"]').click()
    await viewerPage.locator('[data-test="account-menu-toggle"]').click()
    await viewerPage.locator('[data-test="nav-user-page"]').click()
    await expect(viewerPage.locator('[data-test="user-page"]')).toBeVisible()
    await viewerPage.locator('[data-test="user-page-edit"]').click()
    await viewerPage.locator('[data-test="user-page-source"]').fill('# Viewer profile\n\nA short public introduction.')
    await viewerPage.locator('[data-test="user-page-save"]').click()
    await expect(viewerPage.locator('[data-test="user-page-pending"]')).toBeVisible()
    await page.goto('/admin?tab=reviews')
    await expect(page.locator('[data-test="admin-reviews"]')).toContainText('Viewer profile')
    await page.locator('[data-test="admin-review-approve"]').click()
    await viewerPage.reload()
    await expect(viewerPage.locator('[data-test="user-page-html"]')).toContainText('A short public introduction.')
    await viewerPage.locator('[data-test="user-page-history-toggle"]').click()
    await expect(viewerPage.locator('[data-test="user-page-history"]')).toContainText('A short public introduction.')
    await expect(viewerPage.locator('[data-test="nav-create"]')).toHaveCount(0)
    await expect(viewerPage.locator('[data-test="nav-admin"]')).toHaveCount(0)

    await page.locator('[data-test="nav-admin"]').click()
    await page.getByRole('tab', { name: 'Users' }).click()
    const viewerRow = page.locator('[data-test="admin-users"] tr').filter({ hasText: 'viewer@e2e.local' })
    await expect(viewerRow).toBeVisible()
    await viewerRow.locator('select').selectOption('editor')
    await expect(viewerRow.locator('select')).toHaveValue('editor')

    await viewerPage.reload()
    await expect(viewerPage.locator('[data-test="nav-create"]')).toBeVisible()
    await page.locator('[data-test="nav-create"]').click()
    await page.locator('[data-test="create-title"]').fill('Moderation Guide')
    await page.locator('[data-test="create-submit"]').click()
    await page.locator('[data-test="md-source"]').fill('# Moderation Guide\n\nPublished baseline')
    await page.locator('[data-test="save-exit"]').click()
    await expect(page.locator('[data-test="doc-html"]')).toContainText('Published baseline')
    const moderationURL = page.url()
    await viewerPage.goto(moderationURL)
    await viewerPage.locator('[data-test="btn-edit"]').click()
    await viewerPage.locator('[data-test="md-source"]').fill('# Accepted after review\n\nPending contribution body')
    await viewerPage.locator('[data-test="save-exit"]').click()
    await expect(viewerPage.locator('[data-test="doc-html"]')).not.toContainText('Pending contribution body')
    await page.goto('/admin?tab=reviews')
    await expect(page.locator('[data-test="admin-reviews"]')).toContainText('Pending contribution body')
    await page.locator('[data-test="admin-review-document-approve"]').click()
    await viewerPage.reload()
    await expect(viewerPage.locator('[data-test="doc-html"]')).toContainText('Pending contribution body')
    await viewerPage.locator('[data-test="btn-more"]').click()
    await viewerPage.locator('[data-test="btn-report-document"]').click()
    await viewerPage.locator('.el-message-box__input textarea').fill('This article includes unsafe content')
    await viewerPage.locator('.el-message-box__btns .el-button--primary').click()
    await page.goto('/admin?tab=reviews')
    await expect(page.locator('[data-test="admin-reviews"]')).toContainText('This article includes unsafe content')
    await expect(page.locator('[data-test="admin-reviews"]')).toContainText('Moderation Guide')
    await page.locator('[data-test="admin-report-unpublish"]').click()
    await page.locator('.el-message-box__input textarea').fill('Confirmed by review')
    await page.locator('.el-message-box__btns .el-button--primary').click()
    await expect(page.locator('[data-test="admin-reviews"]')).toContainText('Unpublished content')
    await page.locator('[data-test="admin-content-restore"]').click()
    await page.locator('.el-message-box__input textarea').fill('Restored after correction')
    await page.locator('.el-message-box__btns .el-button--primary').click()

    await viewerPage.reload()
    const editorAdminLink = viewerPage.locator('[data-test="nav-admin"]')
    await expect(editorAdminLink).toHaveAttribute('href', '/admin?tab=tree')
    await editorAdminLink.click()
    await expect(viewerPage.locator('[data-test="tab-tree"]')).toBeVisible()
  } finally {
    await viewerContext.close()
  }
})
